apiVersion: v1
kind: Pod
metadata:
  name: docker-build-pod

  labels:
    some-label: some-label-value
spec:
  serviceAccountName: jenkins-admin
  containers:
  - name: jnlp
    env:
    - name: CONTAINER_ENV_VAR
      value: jnlp
  - name: alacrity
    image: us-central1-docker.pkg.dev/devops-353009/devops-docker/polygot:main
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  restartPolicy: Never
  volumes:
   - name: docker-sock
     hostPath:
      path: /var/run/docker.sock
  